### ISSUE TITLE
[BUG] Proximity Feature Not Working

### ISSUE THREAD

**Issue by goddivock** [cybershard/auproximity#25] opened 2020-12-23 15:02 UTC
**Describe the bug**
I was testing this out with a few other people. The proximity feature didn't seem to work as we could always speak to each other, even as ghosts. 

**To Reproduce**

**Expected behavior**
Being able to use the proximity chat feature.

**Screenshots**

**Where are you using the proximity chat?:**
 - Browser [e.g. firefox, chrome, safari] Chrome
 - Platform [e.g. Windows, macOS, Linux, Android, iOS] Windows (the other people used iOS and then I also tried using iOS but it didn't work at all)

**Additional context**
I found this on reddit. We tried following the steps from this reddit post: https://www.reddit.com/r/AmongUs/comments/k65eu4/proximity_voice_chat_is_now_available_for_all/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

Just to for additional context, the way we did it was:

1. I'd make my the lobby on AU
2. Enter the details on AUProximity
3. Send the link to the others (making sure everyone put their exact name)
4. They joined the link (we were usually able to speak immediately, although sometimes with a lot of echo)
5. They joined the lobby (We tried it the other way around as well - joining lobby and then the link, same outcome)
6. We tested it

Also I've only tested on Chrome.

**Comment by edqx** [comment] 2020-12-23 15:03
Following line from the discord server's faq channel:

**Why can I hear everyone around the map?**
Likely because the bot failed to join the game due to a connection issue. Make sure when you press Join Game on auproximity, that you hear a player joining and leaving instantly, this is a main indicator that the bot has successfully and joined and is ready to handle proximity chat. Else, create a brand new lobby and remember to join the proximity chat before starting the game. If you don't hear this noise again, try a few more times and report back here if you're still having issues.

**Comment by goddivock** [comment] 2020-12-23 15:10
Appreciate the quick response! Yes I saw that about the noise but I have not been hearing anything at all. I'll try again, thanks!

**Comment by goddivock** [comment] 2020-12-23 21:36
I tried using Chrome and Firefox but neither seemed to work. I would hear the player pretty much instantly upon joining but the actual proximity feature did not work. Besides connection issues, are there any other possible reasons for this problem? Or could it be that I am doing something wrong in the way I set it up? I briefly described the steps I took to use auproximity in the post above.

**Comment by addshore** [comment] 2021-01-08 18:58
I'v been trying this out (the hosted version at https://auproxydev.herokuapp.com/) over the past weeks and I seem to fairly reproducible make it work on the Asia and US server, but never on Europe.

Not sure if this is an issue with Among us or this tool?
@goddivock did you try different servers? which one were you using?

**Comment by addshore** [comment] 2021-01-08 21:38
I joined the discord, had a chat and someone pointed me to https://edqx-auproxy.herokuapp.com/ which seems to work just fine for the Europe server

**Comment by Ramzh** [comment] 2021-01-13 22:44
> 
> 
> I joined the discord, had a chat and someone pointed me to https://edqx-auproxy.herokuapp.com/ which seems to work just fine for the Europe server

Can confirm this is working for EU tested it today also has slide feature!

**Comment by edqx** [comment] 2021-01-14 12:36
Sorry I didn't see these last few comments, I guess I can close the issue now.

**Closed by edqx** 2021-01-14 12:36 UTC
